export const MonthIndexEnum = new Map([
	['Jan', 1],
	['Feb', 2],
	['Mar', 3],
	['Apr', 4],
	['May', 5],
	['Jun', 6],
	['Jul', 7],
	['Aug', 8],
	['Sep', 9],
	['Oct', 10],
	['Nov', 11],
	['Dec', 12],
]);

export const MonthFullEnum = new Map([
    ['Jan', 'January'],
    ['Feb', 'February'],
    ['Mar', 'March'],
    ['Apr', 'April'],
    ['May', 'May'],
    ['Jun', 'June'],
    ['Jul', 'July'],
    ['Aug', 'August'],
    ['Sep', 'September'],
    ['Oct', 'October'],
    ['Nov', 'November'],
    ['Dec', 'December'],
])

export const OrdinalIndicatorEnum = new Map([
    ['1', 'st'],
    ['2', 'nd'],
    ['3', 'rd'],
    ['4', 'th'],
    ['5', 'th'],
    ['6', 'th'],
    ['7', 'th'],
    ['8', 'th'],
    ['9', 'th'],
    ['10', 'th'],
    ['11', 'th'],
    ['12', 'th'],
    ['13', 'th'],
    ['14', 'th'],
    ['15', 'th'],
    ['16', 'th'],
    ['17', 'th'],
    ['18', 'th'],
    ['19', 'th'],
    ['20', 'th'],
    ['21', 'st'],
    ['22', 'nd'],
    ['23', 'rd'],
    ['24', 'th'],
    ['25', 'th'],
    ['26', 'th'],
    ['27', 'th'],
    ['28', 'th'],
    ['29', 'th'],
    ['30', 'th'],
    ['31', 'st'],
  ]);
